from datetime import datetime
from app.extensions import db


class EmotionRealTime(db.Model):
    __tablename__ = "emotion_real_time"
    id = db.Column(db.BigInteger, primary_key=True, autoincrement=True)
    suspect_id = db.Column(db.String(50), nullable=False, index=True)
    frame = db.Column(db.Integer)
    time_sec = db.Column(db.BigInteger)
    dominant_emotion = db.Column(db.Integer)
    emotion_angry = db.Column(db.Float)
    emotion_disgust = db.Column(db.Float)
    emotion_fear = db.Column(db.Float)
    emotion_happy = db.Column(db.Float)
    emotion_sad = db.Column(db.Float)
    emotion_surprise = db.Column(db.Float)
    emotion_neutral = db.Column(db.Float)
    face_x = db.Column(db.Integer)
    face_y = db.Column(db.Integer)
    face_w = db.Column(db.Integer)
    face_h = db.Column(db.Integer)
    left_eyebrow_x = db.Column(db.Integer)
    left_eyebrow_y = db.Column(db.Integer)
    left_eyebrow_w = db.Column(db.Integer)
    left_eyebrow_h = db.Column(db.Integer)
    right_eyebrow_x = db.Column(db.Integer)
    right_eyebrow_y = db.Column(db.Integer)
    right_eyebrow_w = db.Column(db.Integer)
    right_eyebrow_h = db.Column(db.Integer)
    left_eye_x = db.Column(db.Integer)
    left_eye_y = db.Column(db.Integer)
    left_eye_w = db.Column(db.Integer)
    left_eye_h = db.Column(db.Integer)
    right_eye_x = db.Column(db.Integer)
    right_eye_y = db.Column(db.Integer)
    right_eye_w = db.Column(db.Integer)
    right_eye_h = db.Column(db.Integer)
    mouth_x = db.Column(db.Integer)
    mouth_y = db.Column(db.Integer)
    mouth_w = db.Column(db.Integer)
    mouth_h = db.Column(db.Integer)
    heart_rate = db.Column(db.Integer)
    gaze_direction = db.Column(db.Integer)
    head_pose_pitch = db.Column(db.Float)
    head_pose_yaw = db.Column(db.Float)
    head_pose_roll = db.Column(db.Float)
    attention = db.Column(db.Integer)
    au_inner_brow_raiser = db.Column(db.Float)
    au_outer_brow_raiser = db.Column(db.Float)
    au_brow_furrower = db.Column(db.Float)
    au_upper_eyelid_raiser = db.Column(db.Float)
    au_cheek_raiser = db.Column(db.Float)
    au_nose_wrinkler = db.Column(db.Float)
    au_upper_lip_raiser = db.Column(db.Float)
    au_lip_corner_puller = db.Column(db.Float)
    au_lip_corner_depressor = db.Column(db.Float)
    au_jaw_raiser = db.Column(db.Float)
    au_lip_stretcher = db.Column(db.Float)
    au_lip_compressor = db.Column(db.Float)
    au_lip_parter = db.Column(db.Float)
    au_jaw_dropper = db.Column(db.Float)
    au_eye_closure = db.Column(db.Float)
    left_eye_gaze_horizontal = db.Column(db.Float)
    left_eye_gaze_vertical = db.Column(db.Float)
    right_eye_gaze_horizontal = db.Column(db.Float)
    right_eye_gaze_vertical = db.Column(db.Float)
    create_time = db.Column(db.DateTime, default=datetime.now)
    update_time = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
