import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const viewSource = readFileSync(new URL('../views/SimulationInterrogationView.vue', import.meta.url), 'utf8')
const roomCssSource = readFileSync(new URL('../styles/interrogation-room.css', import.meta.url), 'utf8')
const controlPanelSource = readFileSync(new URL('../components/interrogation/ControlPanel.vue', import.meta.url), 'utf8')
const historyPanelUrl = new URL('../components/interrogation/CaseHistoryPanel.vue', import.meta.url)
const recordingStatusSource = readFileSync(new URL('../components/interrogation/RecordingStatus.vue', import.meta.url), 'utf8')
const voiceWaveformPanelUrl = new URL('../components/interrogation/VoiceWaveformPanel.vue', import.meta.url)
const caseInfoPanelSource = readFileSync(new URL('../components/interrogation/CaseInfoPanel.vue', import.meta.url), 'utf8')
const faceAnalysisPanelSource = readFileSync(new URL('../components/interrogation/FaceAnalysisPanel.vue', import.meta.url), 'utf8')
const au52TablePanelUrl = new URL('../components/interrogation/Au52TablePanel.vue', import.meta.url)
const physiologyPosePanelUrl = new URL('../components/interrogation/PhysiologyPosePanel.vue', import.meta.url)
const suspectVideoPanelSource = readFileSync(new URL('../components/interrogation/SuspectVideoPanel.vue', import.meta.url), 'utf8')
const anomalyWaveformPanelUrl = new URL('../components/interrogation/AnomalyWaveformPanel.vue', import.meta.url)

test('simulation room keeps collapsible case info in the left column and video in the center column', () => {
  assert.match(viewSource, /class="room-column room-left-column"[\s\S]*<CaseInfoPanel[\s\S]*<AnomalyWaveformPanel[\s\S]*<FaceAnalysisPanel[\s\S]*<VoiceWaveformPanel/)
  assert.doesNotMatch(viewSource, /class="room-column room-left-column"[\s\S]*<PhysiologyPosePanel/)
  assert.match(viewSource, /class="room-column room-video-column"[\s\S]*<SuspectVideoPanel[\s\S]*<Au52TablePanel/)
  assert.match(roomCssSource, /\.room-video-column\s+\.video-section[\s\S]*flex:\s*1/)
  assert.match(roomCssSource, /\.room-left-column\s+\.voice-waveform-panel\s*\{[\s\S]*flex:\s*0 0 176px/)
  assert.match(roomCssSource, /\.room-left-column\s+\.voice-waveform-panel\s*\{[\s\S]*margin:\s*12px 14px 14px/)
  assert.match(roomCssSource, /\.room-left-column\s+\.analysis-panel\s*\{[\s\S]*flex:\s*0 0 auto[\s\S]*min-height:\s*0/)

  assert.match(caseInfoPanelSource, /const isCollapsed = ref\(true\)/)
  assert.match(caseInfoPanelSource, /class="case-toggle"/)
  assert.match(caseInfoPanelSource, /:aria-expanded="!isCollapsed"/)
  assert.match(caseInfoPanelSource, /class="case-collapse-body"/)
  assert.match(caseInfoPanelSource, /:class="\{ collapsed: isCollapsed \}"/)
})

test('simulation room removes center chat workflow elements', () => {
  assert.doesNotMatch(viewSource, /ChatTranscript/)
  assert.doesNotMatch(viewSource, /MessageInput/)
  assert.doesNotMatch(viewSource, /StageIndicator/)
  assert.doesNotMatch(viewSource, /SpeechGuidancePanel/)
  assert.doesNotMatch(viewSource, /chat-panel/)
  assert.doesNotMatch(viewSource, /message-count/)
})

test('simulation room places compact controls in the video top horizontal bar', () => {
  assert.match(viewSource, /class="video-stage-header"[\s\S]*caseDetail\?\.title[\s\S]*class="video-toolbar-controls"[\s\S]*<ControlPanel[\s\S]*compact[\s\S]*class="video-stage"/)
  assert.match(viewSource, /:overlay-visible="overlayVisible"/)
  assert.match(viewSource, /@toggle-overlays="toggleOverlays"/)
  assert.match(roomCssSource, /\.video-stage-header\s*\{[\s\S]*display:\s*flex[\s\S]*justify-content:\s*space-between/)
  assert.match(roomCssSource, /\.video-toolbar-controls\s*\{[\s\S]*flex:\s*0 0 auto/)
  assert.doesNotMatch(viewSource, /video-control-overlay/)
  assert.doesNotMatch(roomCssSource, /video-control-overlay/)
  assert.match(controlPanelSource, /compact\?:\s*boolean/)
  assert.match(controlPanelSource, /overlayVisible:\s*boolean/)
  assert.match(controlPanelSource, /toggleOverlays/)
  assert.match(controlPanelSource, /隐藏叠加|显示叠加/)
  assert.match(controlPanelSource, /finishBaseline/)
  assert.match(controlPanelSource, /基准检测结束/)
})

test('AU52 table is fixed below the center demo video with device status at bottom right', () => {
  assert.ok(existsSync(au52TablePanelUrl), `${fileURLToPath(au52TablePanelUrl)} should exist`)
  assert.match(viewSource, /class="video-stage"[\s\S]*<SuspectVideoPanel[\s\S]*:show-overlays="overlayVisible"[\s\S]*<Au52TablePanel[\s\S]*v-if="overlayVisible"[\s\S]*:asr-status="asrStatus"[\s\S]*:face-status="faceStatus"[\s\S]*<\/div>/)

  const au52TableSource = readFileSync(au52TablePanelUrl, 'utf8')
  assert.match(au52TableSource, /buildAuIntensityItems\(props\.result\)/)
  assert.match(au52TableSource, /au52-table/)
  assert.match(au52TableSource, /class="au52-status-grid"/)
  assert.match(au52TableSource, /视频链路/)
  assert.match(au52TableSource, /音频链路/)
  assert.match(au52TableSource, /视频帧/)
  assert.match(au52TableSource, /音频包/)
  assert.match(au52TableSource, /position:\s*absolute/)
  assert.match(au52TableSource, /left:\s*18px/)
  assert.match(au52TableSource, /right:\s*18px/)
  assert.match(au52TableSource, /bottom:\s*12px/)
  assert.match(au52TableSource, /padding:\s*8px/)
  assert.match(au52TableSource, /border-radius:\s*7px/)
  assert.match(au52TableSource, /background:\s*rgba\(0, 0, 0, 0\.42\)/)
  assert.match(au52TableSource, /grid-template-columns:\s*repeat\(10, minmax\(0, 1fr\)\)/)
  assert.match(au52TableSource, /grid-template-columns:\s*minmax\(0, 1fr\) 28px/)
  assert.match(au52TableSource, /min-height:\s*18px/)
  assert.match(au52TableSource, /font-size:\s*9px/)
  assert.match(au52TableSource, /\.au52-cell strong\s*\{[\s\S]*font-size:\s*10px/)
  assert.match(au52TableSource, /margin-left:\s*auto/)
  assert.match(au52TableSource, /width:\s*min\(300px, 100%\)/)
  assert.match(au52TableSource, /\.au52-status-item span\s*\{[\s\S]*font-size:\s*9px/)
  assert.match(au52TableSource, /\.au52-status-item strong\s*\{[\s\S]*font-size:\s*11px/)
  assert.doesNotMatch(au52TableSource, /AU52 强度表/)
  assert.doesNotMatch(au52TableSource, /flex:\s*0 0 auto/)
  assert.doesNotMatch(au52TableSource, /v-if="auItems\.length"/)
  assert.doesNotMatch(au52TableSource, /au52-empty/)
})

test('physiology pose data is embedded on the left side of the video frame', () => {
  assert.ok(existsSync(physiologyPosePanelUrl), `${fileURLToPath(physiologyPosePanelUrl)} should exist`)
  assert.match(caseInfoPanelSource, /class="case-info-strip compact"/)
  assert.doesNotMatch(caseInfoPanelSource, /overflow-y:\s*auto/)

  const physiologyPoseSource = readFileSync(physiologyPosePanelUrl, 'utf8')
  assert.match(physiologyPoseSource, /生理与姿态/)
  assert.match(physiologyPoseSource, /heart_rate/)
  assert.match(physiologyPoseSource, /headPoseItems/)
  assert.match(physiologyPoseSource, /embedded\?:\s*boolean/)
  assert.match(physiologyPoseSource, /class="\{ embedded: props\.embedded \}"/)
  assert.match(physiologyPoseSource, /\.physiology-pose-panel\.embedded[\s\S]*width:\s*132px/)
  assert.match(physiologyPoseSource, /\.physiology-pose-panel\.embedded[\s\S]*padding:\s*7px/)
  assert.match(physiologyPoseSource, /\.physiology-grid\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\)/)
  assert.match(physiologyPoseSource, /\.embedded \.physiology-grid\s*\{[\s\S]*gap:\s*4px/)
  assert.match(physiologyPoseSource, /\.embedded \.physiology-item\s*\{[\s\S]*min-height:\s*30px[\s\S]*padding:\s*4px 6px/)
  assert.match(physiologyPoseSource, /\.embedded \.physiology-item span\s*\{[\s\S]*font-size:\s*9px/)
  assert.match(physiologyPoseSource, /\.embedded \.physiology-item strong\s*\{[\s\S]*font-size:\s*10px/)
  assert.match(suspectVideoPanelSource, /import PhysiologyPosePanel/)
  assert.match(suspectVideoPanelSource, /showOverlays:\s*boolean/)
  assert.match(suspectVideoPanelSource, /v-if="stream && props\.showOverlays"/)
  assert.match(suspectVideoPanelSource, /class="video-physiology-overlay"[\s\S]*<PhysiologyPosePanel[\s\S]*embedded[\s\S]*:result="result"/)
  assert.match(suspectVideoPanelSource, /width:\s*132px/)
  assert.doesNotMatch(physiologyPoseSource, /overflow-y:\s*auto/)
  assert.doesNotMatch(faceAnalysisPanelSource, /生理与姿态/)
  assert.doesNotMatch(faceAnalysisPanelSource, /设备状态/)
})

test('anomaly waveform panel sits between physiology pose and device status', () => {
  assert.ok(existsSync(anomalyWaveformPanelUrl), `${fileURLToPath(anomalyWaveformPanelUrl)} should exist`)
  assert.match(viewSource, /<CaseInfoPanel[\s\S]*<AnomalyWaveformPanel[\s\S]*<FaceAnalysisPanel/)

  const anomalyWaveformSource = readFileSync(anomalyWaveformPanelUrl, 'utf8')
  assert.match(anomalyWaveformSource, /状态监测/)
  assert.doesNotMatch(anomalyWaveformSource, /异常波形/)
  assert.match(anomalyWaveformSource, /<svg/)
  assert.match(anomalyWaveformSource, /<polyline/)
  assert.match(anomalyWaveformSource, /告警状态/)
  assert.match(anomalyWaveformSource, /\.anomaly-waveform-panel\s*\{[\s\S]*min-height:\s*304px/)
  assert.match(anomalyWaveformSource, /\.anomaly-waveform-panel\s*\{[\s\S]*flex:\s*1 1 0/)
  assert.match(anomalyWaveformSource, /\.anomaly-waveform-panel\s*\{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/)
  assert.match(anomalyWaveformSource, /\.anomaly-waveform-chart\s*\{[\s\S]*flex:\s*1 1 auto[\s\S]*min-height:\s*126px/)
  assert.doesNotMatch(anomalyWaveformSource, /\.anomaly-waveform-chart\s*\{[\s\S]*\n\s*height:\s*126px/)
  assert.match(anomalyWaveformSource, /\.anomaly-domain-grid\s*\{[\s\S]*flex:\s*0 0 auto[\s\S]*grid-auto-rows:\s*minmax\(44px, auto\)/)
  assert.match(anomalyWaveformSource, /\.anomaly-alert-strip\s*\{[\s\S]*flex:\s*0 0 30px/)
  assert.doesNotMatch(anomalyWaveformSource, /v-if="alertItems\.length"/)
  assert.doesNotMatch(anomalyWaveformSource, /overflow-y:\s*auto/)
})

test('face analysis panel keeps the section title free of dominant emotion text', () => {
  assert.match(faceAnalysisPanelSource, /<span>微表情分析<\/span>/)
  assert.doesNotMatch(faceAnalysisPanelSource, /dominantEmotion/)
  assert.doesNotMatch(faceAnalysisPanelSource, /FACE_EMOTION_LABELS/)
  assert.doesNotMatch(faceAnalysisPanelSource, /<span class="muted">\{\{[^}]+Emotion[^}]*\}\}<\/span>/)
})

test('suspect video panel exposes a microphone status badge at the upper right', () => {
  assert.match(viewSource, /<SuspectVideoPanel[\s\S]*:asr-status="asrStatus"/)
  assert.match(suspectVideoPanelSource, /asrStatus:\s*SocketStatus/)
  assert.match(suspectVideoPanelSource, /microphoneStatusLabel/)
  assert.match(suspectVideoPanelSource, /class="microphone-badge"/)
  assert.match(suspectVideoPanelSource, /class="microphone-glyph"/)
  assert.match(suspectVideoPanelSource, /class="microphone-status-text"/)
  assert.match(suspectVideoPanelSource, /采集中/)
  assert.match(suspectVideoPanelSource, /已断开/)
  assert.match(suspectVideoPanelSource, /title="microphoneStatusLabel"/)
  assert.match(suspectVideoPanelSource, /\.microphone-icon-shell\s*\{[\s\S]*width:\s*28px[\s\S]*height:\s*28px[\s\S]*padding:\s*0/)
  assert.match(suspectVideoPanelSource, /\.microphone-glyph\s*\{[\s\S]*width:\s*7px[\s\S]*height:\s*10px/)
  assert.match(suspectVideoPanelSource, /\.video-status-stack\s*\{[\s\S]*top:\s*16px[\s\S]*right:\s*16px/)
})

test('simulation room keeps voice waveform at the lower left and removes it from the right column', () => {
  assert.match(viewSource, /class="room-column room-left-column"[\s\S]*<VoiceWaveformPanel[\s\S]*:sent-chunks="sentChunks"[\s\S]*:status="asrStatus"[\s\S]*:volume="voiceVolume"[\s\S]*:waveform="voiceWaveform"/)
  assert.match(viewSource, /class="right-panel"[\s\S]*<CaseHistoryPanel[\s\S]*<RecordingStatus[\s\S]*<\/div>/)
  assert.doesNotMatch(viewSource, /class="right-panel"[\s\S]*<VoiceWaveformPanel/)
  assert.doesNotMatch(viewSource, /EvidencePanel/)
  assert.doesNotMatch(viewSource, /RuntimeLogPanel/)
  assert.doesNotMatch(viewSource, /QuickQueryPanel/)
  assert.doesNotMatch(viewSource, /runtimeLogs/)
  assert.doesNotMatch(viewSource, /evidence_chain|interrogation_points/)
  assert.ok(existsSync(voiceWaveformPanelUrl), `${fileURLToPath(voiceWaveformPanelUrl)} should exist`)
})

test('recording status keeps latest transcript text at the top without scroll-only reading', () => {
  assert.match(recordingStatusSource, /latestSegment/)
  assert.match(recordingStatusSource, /class="latest-transcript"/)
  const latestTranscriptCss = recordingStatusSource.match(/\.latest-transcript\s*\{[^}]*\}/)?.[0] ?? ''
  assert.match(latestTranscriptCss, /height:\s*76px/)
  assert.match(latestTranscriptCss, /overflow-y:\s*auto/)
  assert.doesNotMatch(recordingStatusSource, /max-height:\s*180px/)
})

test('recording status renders ASR extracted keywords by category', () => {
  assert.match(viewSource, /:keywords="asrKeywords"/)
  assert.match(viewSource, /:keyword-status="asrKeywordStatus"/)
  assert.match(recordingStatusSource, /keywords:\s*AsrKeywordItem\[\]/)
  assert.match(recordingStatusSource, /keywordStatus:\s*AsrKeywordStatus/)
  assert.match(recordingStatusSource, /class="keyword-panel"/)
  assert.match(recordingStatusSource, /class="keyword-tag"/)
  assert.match(recordingStatusSource, /CATEGORY_TAG_TYPES/)
  assert.match(recordingStatusSource, /关键词提炼/)
})

test('recording status inserts speaker transcript between latest transcript and keywords', () => {
  assert.match(viewSource, /const speakerSegments = computed\(\(\) => room\.asrSocket\.speakerSegments\.value\)/)
  assert.match(viewSource, /const speakerDiarizationStatus = computed\(\(\) => room\.asrSocket\.speakerStatus\.value\)/)
  assert.match(viewSource, /:speaker-segments="speakerSegments"/)
  assert.match(viewSource, /:speaker-status="speakerDiarizationStatus"/)
  assert.match(recordingStatusSource, /AsrSpeakerTranscriptSegment/)
  assert.match(recordingStatusSource, /AsrSpeakerDiarizationStatus/)
  assert.match(recordingStatusSource, /speakerSegments:\s*AsrSpeakerTranscriptSegment\[\]/)
  assert.match(recordingStatusSource, /speakerStatus:\s*AsrSpeakerDiarizationStatus/)
  assert.match(recordingStatusSource, /recentSpeakerSegments/)
  assert.match(recordingStatusSource, /pickRecentSpeakerSegments\(props\.speakerSegments,\s*6\)/)
  assert.match(recordingStatusSource, /人声分离/)
  assert.match(recordingStatusSource, /等待人声分离结果/)
  assert.match(recordingStatusSource, /人声分离暂不可用/)
  assert.doesNotMatch(recordingStatusSource, /说话人转写/)
  assert.match(recordingStatusSource, /getSpeakerToneClass\(segment\.speaker\)/)
  assert.match(recordingStatusSource, /说话人\{\{ segment\.speaker \|\| 'unknown' \}\}：/)
  assert.doesNotMatch(recordingStatusSource, /未匹配到转写文本/)
  assert.doesNotMatch(recordingStatusSource, /segment\.start }} - {{ segment\.end/)
  assert.ok(recordingStatusSource.indexOf('人声分离') < recordingStatusSource.indexOf('关键词提炼'))
})

test('right column lets keyword extraction fill the remaining right-side space', () => {
  const keywordPanelCss = recordingStatusSource.match(/\.keyword-panel\s*\{[^}]*\}/)?.[0] ?? ''
  const speakerListCss = recordingStatusSource.match(/\.speaker-list\s*\{[^}]*\}/)?.[0] ?? ''

  assert.match(roomCssSource, /\.right-panel\s*\{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column[\s\S]*overflow:\s*hidden/)
  assert.match(recordingStatusSource, /class="panel-section recording-status-panel"/)
  assert.match(recordingStatusSource, /\.recording-status-panel\s*\{[\s\S]*flex:\s*1 1 auto[\s\S]*overflow:\s*hidden/)
  assert.match(recordingStatusSource, /\.latest-transcript\s*\{[\s\S]*height:\s*76px[\s\S]*overflow-y:\s*auto/)
  assert.match(recordingStatusSource, /\.transcript-empty\s*\{[\s\S]*height:\s*76px/)
  assert.match(recordingStatusSource, /pickRecentSpeakerSegments\(props\.speakerSegments,\s*6\)/)
  assert.match(recordingStatusSource, /\.speaker-panel\s*\{[\s\S]*height:\s*156px[\s\S]*overflow:\s*hidden/)
  assert.match(speakerListCss, /grid-template-rows:\s*repeat\(6, minmax\(0, 1fr\)\)/)
  assert.match(speakerListCss, /overflow:\s*hidden/)
  assert.doesNotMatch(speakerListCss, /overflow-y:\s*auto/)
  assert.match(keywordPanelCss, /flex:\s*1 1 0/)
  assert.match(keywordPanelCss, /min-height:\s*0/)
  assert.match(keywordPanelCss, /overflow:\s*hidden/)
  assert.doesNotMatch(keywordPanelCss, /height:\s*140px/)
  assert.match(recordingStatusSource, /\.keyword-list\s*\{[\s\S]*overflow-y:\s*auto/)
  assert.doesNotMatch(recordingStatusSource, /class="segment-list"/)
  assert.doesNotMatch(recordingStatusSource, /segment\.time/)
})

test('recording status opens a delayed themed right-side lookup drawer for professional keyword categories', () => {
  assert.match(recordingStatusSource, /KEYWORD_LOOKUP_PAGES/)
  assert.match(recordingStatusSource, /KEYWORD_LOOKUP_LOADING_PAGES/)
  assert.match(recordingStatusSource, /resolveLookupKeywordCategory/)
  assert.match(recordingStatusSource, /getLookupKeywordDisplayText/)
  assert.match(recordingStatusSource, /银行卡/)
  assert.match(recordingStatusSource, /手机号/)
  assert.match(recordingStatusSource, /车牌号/)
  assert.match(recordingStatusSource, /activeKeywordLookup/)
  assert.match(recordingStatusSource, /loadingKeywordLookup/)
  assert.match(recordingStatusSource, /currentKeywordLookup/)
  assert.match(recordingStatusSource, /lookupTimer/)
  assert.match(recordingStatusSource, /openKeywordLookup/)
  assert.match(recordingStatusSource, /closeKeywordLookup/)
  assert.match(recordingStatusSource, /KEYWORD_LOOKUP_LOADING_DURATION_MS = 5000/)
  assert.match(recordingStatusSource, /window\.setTimeout\([\s\S]*KEYWORD_LOOKUP_LOADING_DURATION_MS/)
  assert.match(recordingStatusSource, /window\.clearTimeout\(lookupTimer\)/)
  assert.match(recordingStatusSource, /getKeywordTagType/)
  assert.match(recordingStatusSource, /handleKeywordKeydown/)
  assert.match(recordingStatusSource, /window\.addEventListener\('keydown', handleKeywordKeydown\)/)
  assert.match(recordingStatusSource, /window\.removeEventListener\('keydown', handleKeywordKeydown\)/)

  assert.match(recordingStatusSource, /<button[\s\S]*class="keyword-tag keyword-action"[\s\S]*@click="openKeywordLookup\(keyword\)"/)
  assert.match(recordingStatusSource, /isKeywordLoading\(keyword\)/)
  assert.doesNotMatch(recordingStatusSource, /keyword-querying-text/)
  assert.match(recordingStatusSource, /v-else[\s\S]*class="keyword-tag"/)
  assert.match(recordingStatusSource, /<Transition name="keyword-drawer"/)
  assert.match(recordingStatusSource, /v-if="currentKeywordLookup"[\s\S]*class="keyword-detail-overlay"[\s\S]*@click="closeKeywordLookup"/)
  assert.match(recordingStatusSource, /class="keyword-detail-drawer"[\s\S]*role="dialog"[\s\S]*aria-modal="true"/)
  assert.match(recordingStatusSource, /aria-label="关闭关键词详情"/)
  assert.match(recordingStatusSource, /v-if="loadingKeywordLookup"[\s\S]*class="keyword-lookup-loading-page"/)
  assert.match(recordingStatusSource, /class="keyword-lookup-loading-orbit"/)
  assert.match(recordingStatusSource, /class="keyword-lookup-scanline"/)
  assert.match(recordingStatusSource, /查询中/)
  assert.match(recordingStatusSource, /正在核验信息/)
  assert.match(recordingStatusSource, /class="keyword-lookup-page"/)
  assert.match(recordingStatusSource, /class="keyword-lookup-status"/)
  assert.match(recordingStatusSource, /class="keyword-lookup-source"/)
  assert.match(recordingStatusSource, /class="keyword-lookup-query"/)
  assert.match(recordingStatusSource, /class="keyword-lookup-time"/)
  assert.match(recordingStatusSource, /class="keyword-lookup-verification"/)
  assert.match(recordingStatusSource, /v-for="(?:\(\s*)?item(?:\s*\))?\s+in activeKeywordLookup\.page\.fields"/)
  assert.doesNotMatch(recordingStatusSource, /activeKeywordLookup\.category\s*}}\s*查询结果/)
  assert.doesNotMatch(recordingStatusSource, /身份证信息核验/)
  assert.doesNotMatch(recordingStatusSource, /车次轨迹查询/)

  assert.match(recordingStatusSource, /银行卡信息核验/)
  assert.match(recordingStatusSource, /账户命中/)
  assert.match(recordingStatusSource, /正在调取资金管控平台/)
  assert.match(recordingStatusSource, /资金管控平台/)
  assert.match(recordingStatusSource, /正在通过资金管控平台核验银行卡账户信息，请稍候/)
  assert.match(recordingStatusSource, /BC-20260525-582913/)
  assert.match(recordingStatusSource, /银行卡号/)
  assert.match(recordingStatusSource, /6222 2913 2913 1234/)
  assert.match(recordingStatusSource, /中国工商银行/)
  assert.match(recordingStatusSource, /银行卡账户信息匹配/)

  assert.match(recordingStatusSource, /手机号实名核验/)
  assert.match(recordingStatusSource, /实名命中/)
  assert.match(recordingStatusSource, /正在调取手机信息管理/)
  assert.match(recordingStatusSource, /手机信息管理/)
  assert.match(recordingStatusSource, /正在通过手机信息管理核验手机号实名信息，请稍候/)
  assert.doesNotMatch(recordingStatusSource, /正在调取开普勒云砚/)
  assert.doesNotMatch(recordingStatusSource, /正在通过开普勒云砚核验手机号实名信息，请稍候/)
  assert.match(recordingStatusSource, /MP-20260525-672914/)
  assert.match(recordingStatusSource, /13829135678/)
  assert.match(recordingStatusSource, /入网时间/)
  assert.match(recordingStatusSource, /手机号实名信息匹配/)

  assert.match(recordingStatusSource, /车辆信息查询/)
  assert.match(recordingStatusSource, /车辆命中/)
  assert.match(recordingStatusSource, /正在调取公安部云搜索/)
  assert.match(recordingStatusSource, /公安部云搜索/)
  assert.match(recordingStatusSource, /正在通过公安部云搜索查询机动车登记信息，请稍候/)
  assert.match(recordingStatusSource, /VH-20260525-451028/)
  assert.match(recordingStatusSource, /违法未处理/)
  assert.match(recordingStatusSource, /0 条/)
  assert.match(recordingStatusSource, /沪A·12345/)
  assert.match(recordingStatusSource, /车辆登记信息匹配/)
  assert.doesNotMatch(recordingStatusSource, /138\*\*\*\*5678/)

  assert.match(recordingStatusSource, /\.keyword-detail-overlay\s*\{[\s\S]*position:\s*fixed[\s\S]*inset:\s*0/)
  assert.match(recordingStatusSource, /\.keyword-detail-drawer\s*\{[\s\S]*position:\s*absolute[\s\S]*top:\s*20%[\s\S]*right:\s*0/)
  assert.match(recordingStatusSource, /\.keyword-detail-drawer\s*\{[\s\S]*height:\s*clamp\(360px, 42vh, 440px\)/)
  assert.doesNotMatch(recordingStatusSource, /\.keyword-detail-drawer\s*\{[\s\S]*height:\s*100%/)
  assert.match(recordingStatusSource, /\.keyword-action\s*\{[\s\S]*cursor:\s*pointer/)
  assert.match(recordingStatusSource, /\.keyword-detail-drawer\s*\{[\s\S]*var\(--room-panel-bg-strong\)/)
  assert.match(recordingStatusSource, /\.keyword-drawer-enter-from[\s\S]*transform:\s*translateX\(100%\)/)
  assert.match(recordingStatusSource, /\.keyword-drawer-leave-to[\s\S]*transform:\s*translateX\(100%\)/)
})

test('recording status keeps keyword lookup results compact without scrolling', () => {
  const keywordLookupPageCss = recordingStatusSource.match(/\.keyword-lookup-page\s*\{[^}]*\}/)?.[0] ?? ''
  const keywordLookupMetaCss = recordingStatusSource.match(/\.keyword-lookup-meta\s*\{[^}]*\}/)?.[0] ?? ''
  const keywordDetailListCss = recordingStatusSource.match(/\.keyword-detail-list\s*\{[^}]*\}/)?.[0] ?? ''
  const keywordDetailItemCss = recordingStatusSource.match(/\.keyword-detail-item\s*\{[^}]*\}/)?.[0] ?? ''

  assert.match(keywordLookupPageCss, /overflow:\s*hidden/)
  assert.doesNotMatch(keywordLookupPageCss, /overflow-y:\s*auto/)
  assert.match(keywordLookupMetaCss, /grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(keywordLookupPageCss, /grid-template-areas:\s*"status meta"[\s\S]*"summary meta"[\s\S]*"details details"[\s\S]*"verify verify"/)
  assert.match(keywordDetailListCss, /grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(keywordDetailItemCss, /grid-template-columns:\s*52px minmax\(0, 1fr\)/)
})

test('voice waveform panel renders realtime audio as a macOS editor styled project-themed waveform', () => {
  assert.ok(existsSync(voiceWaveformPanelUrl), `${fileURLToPath(voiceWaveformPanelUrl)} should exist`)

  const voiceWaveformSource = readFileSync(voiceWaveformPanelUrl, 'utf8')
  assert.match(voiceWaveformSource, /音频波形可视化/)
  assert.match(voiceWaveformSource, /class="section-title voice-editor-toolbar"/)
  assert.match(voiceWaveformSource, /class="voice-window-controls"/)
  assert.match(voiceWaveformSource, /aria-hidden="true"/)
  assert.match(voiceWaveformSource, /class="voice-window-dot danger"/)
  assert.match(voiceWaveformSource, /class="voice-window-dot warning"/)
  assert.match(voiceWaveformSource, /class="voice-window-dot success"/)
  assert.match(voiceWaveformSource, /<svg/)
  assert.match(voiceWaveformSource, /voiceThemeGradient/)
  assert.match(voiceWaveformSource, /stop-color="var\(--room-primary\)"/)
  assert.match(voiceWaveformSource, /stop-color="var\(--room-teal\)"/)
  assert.match(voiceWaveformSource, /<polyline/)
  assert.match(voiceWaveformSource, /linePoints/)
  assert.match(voiceWaveformSource, /viewBox="0 0 120 56"/)
  assert.match(voiceWaveformSource, /WAVEFORM_VIEWBOX_HEIGHT = 56/)
  assert.match(voiceWaveformSource, /\.voice-waveform-panel\s*\{[\s\S]*var\(--room-border\)[\s\S]*var\(--room-panel-bg-strong\)[\s\S]*var\(--room-panel-bg-muted\)/)
  assert.match(voiceWaveformSource, /\.voice-waveform-panel \.section-title\s*\{[\s\S]*#c4b5fd/)
  assert.match(voiceWaveformSource, /\.voice-editor-toolbar\s*\{[\s\S]*grid-template-columns:\s*auto minmax\(0, 1fr\) auto/)
  assert.match(voiceWaveformSource, /\.voice-window-dot\.danger\s*\{[\s\S]*var\(--room-danger\)/)
  assert.match(voiceWaveformSource, /\.voice-window-dot\.warning\s*\{[\s\S]*var\(--room-amber\)/)
  assert.match(voiceWaveformSource, /\.voice-window-dot\.success\s*\{[\s\S]*var\(--room-success\)/)
  assert.match(voiceWaveformSource, /\.voice-meter-fill\s*\{[\s\S]*var\(--room-primary\)[\s\S]*var\(--room-teal\)/)
  assert.match(voiceWaveformSource, /\.waveform-line-stage\s*\{[\s\S]*var\(--room-border\)[\s\S]*rgba\(5, 8, 22, 0\.52\)/)
  assert.match(voiceWaveformSource, /\.waveform-glow\s*\{[\s\S]*rgba\(45, 212, 191, 0\.28\)/)
  assert.match(voiceWaveformSource, /\.waveform-line\s*\{[\s\S]*stroke:\s*url\("#voiceThemeGradient"\)/)
  assert.doesNotMatch(voiceWaveformSource, /playheadPosition|isPlayheadActive|waveform-playhead/)
  assert.doesNotMatch(voiceWaveformSource, /#60a5fa/)
  assert.doesNotMatch(voiceWaveformSource, /voiceLineGradient/)
  assert.doesNotMatch(voiceWaveformSource, /#1f2023|#141416|#202124|#121316|#2c2c2e|#8e8e93|#d1d5db|#f5f5f7/)
  assert.doesNotMatch(voiceWaveformSource, /waveform-bar/)
})

test('case history panel renders an in-memory face timeline without record fields', () => {
  assert.ok(existsSync(historyPanelUrl), `${fileURLToPath(historyPanelUrl)} should exist`)

  const historyPanelSource = readFileSync(historyPanelUrl, 'utf8')
  assert.match(viewSource, /faceTimelineBuffer/)
  assert.match(viewSource, /faceTimelineFrames/)
  assert.match(viewSource, /captureFaceTimelineFrame/)
  assert.match(viewSource, /publishFaceTimelineMinute/)
  assert.match(viewSource, /startFaceTimelineCapture/)
  assert.match(viewSource, /stopFaceTimelineCapture/)
  assert.match(viewSource, /window\.setInterval\(captureFaceTimelineFrame,\s*1000\)/)
  assert.match(viewSource, /window\.setInterval\(publishFaceTimelineMinute,\s*60_000\)/)
  assert.match(viewSource, /faceTimelineBuffer\.value = \[\]/)
  assert.match(viewSource, /onBeforeUnmount\(stopFaceTimelineCapture\)/)
  assert.match(viewSource, /<CaseHistoryPanel[\s\S]*:face-frames="faceTimelineFrames"/)
  assert.match(historyPanelSource, /历史记录/)
  assert.match(historyPanelSource, /const isCollapsed = ref\(false\)/)
  assert.match(historyPanelSource, /class="history-toggle"/)
  assert.match(historyPanelSource, /:aria-expanded="!isCollapsed"/)
  assert.match(historyPanelSource, /class="history-collapse-body"/)
  assert.match(historyPanelSource, /:class="\{ collapsed: isCollapsed \}"/)
  assert.match(historyPanelSource, /faceFrames:\s*string\[\]/)
  assert.match(historyPanelSource, /visibleFaceFrames/)
  assert.match(historyPanelSource, /slice\(-18\)/)
  assert.match(historyPanelSource, /placeholderSlots = Array\.from\(\{ length: 18 \}/)
  assert.match(historyPanelSource, /face-timeline-grid/)
  assert.match(historyPanelSource, /face-timeline-avatar/)
  assert.match(historyPanelSource, /v-for="\(\s*frame,\s*index\s*\) in visibleFaceFrames"/)
  assert.match(historyPanelSource, /object-fit:\s*cover/)
  assert.match(historyPanelSource, /\.history-panel\s*\{[\s\S]*height:\s*220px/)
  assert.match(historyPanelSource, /\.history-panel\.collapsed\s*\{[\s\S]*height:\s*42px/)
  assert.match(historyPanelSource, /\.face-timeline-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(6, minmax\(0, 1fr\)\)/)
  assert.match(historyPanelSource, /\.face-timeline-grid\s*\{[\s\S]*grid-template-rows:\s*repeat\(3, minmax\(0, 1fr\)\)/)
  assert.doesNotMatch(historyPanelSource, /grid-template-columns:\s*repeat\(9/)
  assert.doesNotMatch(historyPanelSource, /recentRecords/)
  assert.doesNotMatch(historyPanelSource, /编号/)
  assert.doesNotMatch(historyPanelSource, /案情摘要/)
  assert.doesNotMatch(historyPanelSource, /类型/)
  assert.doesNotMatch(historyPanelSource, /证据链|审讯要点/)
})
